"""Generate .env.template files from the union of multiple env files."""

from __future__ import annotations

from pathlib import Path

from .parser import EnvFile


def generate_template(
    env_files: list[EnvFile],
    show_values: bool = False,
    comment_sources: bool = True,
) -> str:
    """Build a .env.template string from the union of all env files.

    Each variable appears exactly once. A comment above each key lists
    which source environments define it, so developers know which keys
    are common vs environment-specific.

    Args:
        env_files: Parsed environment files to merge.
        show_values: If True, include the value from the first env that
                     defines each key (as a default). Otherwise empty string.
        comment_sources: If True, add # [in: env1, env2] comments.

    Returns:
        Template string suitable for writing to .env.example / .env.template.
    """
    if not env_files:
        return "# Empty — no environment files were provided.\n"

    # Collect all keys and which envs have them, preserving insertion order
    key_sources: dict[str, list[str]] = {}
    key_values: dict[str, str] = {}

    for ef in env_files:
        for key, value in ef.variables.items():
            if key not in key_sources:
                key_sources[key] = []
                key_values[key] = value
            key_sources[key].append(ef.label)

    all_labels = [ef.label for ef in env_files]
    lines: list[str] = [
        "# Auto-generated by envdrift template",
        f"# Sources: {', '.join(all_labels)}",
        "#",
        "# Keys marked [all] are present in every environment.",
        "# Keys marked [partial] are only present in some environments.",
        "",
    ]

    # Group: keys present in all envs first, then partial
    all_keys = [k for k, srcs in key_sources.items() if len(srcs) == len(env_files)]
    partial_keys = [k for k, srcs in key_sources.items() if len(srcs) < len(env_files)]

    def _render_section(keys: list[str], section_tag: str) -> None:
        if not keys:
            return
        lines.append(f"# ── {section_tag} ─────────────────────────────────────────────")
        for key in sorted(keys):
            srcs = key_sources[key]
            if comment_sources and len(srcs) < len(env_files):
                missing = [lbl for lbl in all_labels if lbl not in srcs]
                lines.append(f"# present in: {', '.join(srcs)}  |  missing from: {', '.join(missing)}")
            value = key_values[key] if show_values else ""
            lines.append(f"{key}={value}")
        lines.append("")

    _render_section(all_keys, "present in all environments")
    _render_section(partial_keys, "partial — not in every environment")

    return "\n".join(lines)


def write_template(
    env_files: list[EnvFile],
    output_path: Path,
    show_values: bool = False,
) -> int:
    """Write a .env.template to *output_path*.

    Args:
        env_files: Parsed env files to merge.
        output_path: Destination file path.
        show_values: Whether to include current values as defaults.

    Returns:
        Number of unique keys written.
    """
    content = generate_template(env_files, show_values=show_values)
    output_path.write_text(content, encoding="utf-8")
    # Count non-comment, non-empty lines that look like KEY=
    count = sum(1 for line in content.splitlines() if "=" in line and not line.startswith("#"))
    return count
